/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz4a;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    private static final String Employee = null;

    // ตัวอย่าง 1 ให้สร้าง Employee Employee(1, "John Doe", 50000)
    // และตรวจสอบว่าเงินเดือน เป็น 50000
    @Test
    void createEmployee() {
        Employee employee = new Employee(0, null, 0);
        this.employeeId(1);
        this.name("John Doe");
        this.salary(50000);
        assertEquals(captureDisplayOutput(Employee), "emplotyeeId : 1\nname : John Doe\nsalary : 50000");

    }

    private Object captureDisplayOutput(String employee2) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'captureDisplayOutput'");
    }

    private void salary(int i) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'salary'");
    }

    private void name(String string) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'name'");
    }

    private void employeeId(int i) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'employeeId'");
    }

    private void employeeId(String string) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'employeeId'");
    }

    // ข้อ 2 ตรวจสอบว่า Salary ตั้งให้ติดลบไม่ได้
    @Test
    void SalaryCannotBeNegative() {

    }

    // ข้อ 3 ตรวจสอบว่า Bonus เป็น 20% ของ เงินเดือน(Salary)
    // ต้องมีการแก้ไข code ใน Manager.java ให้ถูกต้อง
    @Test
    void Bonus20() {

    }
}